In [15]:
import numpy as np

In [16]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])

In [17]:
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [18]:
print(x)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [19]:
y = np.array([[0],[0],[0],[1]])

In [20]:
synapse0 = np.random.random((2,1))

In [21]:
synapse0

array([[0.14732252],
       [0.36203988]])

In [22]:
bias = 0.3
lr = 0.6

In [23]:
def nlinear(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))


In [26]:
for i in range(100000):
    layer0 = x
    layer1 = nlinear(np.dot(layer0,synapse0)+bias)
    layer1_error = y-layer1
    layer1_delta = layer1_error*nlinear(layer1,True)
    synapse0 += np.dot(layer0.T,layer1_delta)
    synapse0 = synapse0*lr
    bias += lr*layer1_delta
    

In [27]:
print(layer1)

[[0.00290377]
 [0.00290379]
 [0.00290379]
 [0.99709641]]
