In [1]:
import numpy as np
import matplotlib.pyplot as pt
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [72]:
def nlinear(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))


In [73]:
x= np.array([
            [0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])

y = np.array ([[0,0,1,1]]).T

In [83]:
synapse0 = np.random.random((3,1))

In [84]:
print(synapse0)

[[0.30233257]
 [0.14675589]
 [0.09233859]]


In [85]:
for i in range(1000):
    layer0 = x
    layer1 = nlinear(np.dot(layer0,synapse0))
    layer1_error = y-layer1
    layer1_delta=layer1_error*nlinear(layer1,True)
    synapse0 += np.dot(layer0.T,layer1_delta)
    

In [87]:
print(layer1)
print(y)

[[0.03189135]
 [0.02572489]
 [0.97911982]
 [0.97408378]]
[[0]
 [0]
 [1]
 [1]]
